### ISSUE TITLE
결혼 생활과 public node로만 이루어진 network 문제

### ISSUE THREAD

**Issue by koyang2e** [johngrib/johngrib.github.io#100]
이게 번역 글은 아니지요? 영어가 원문이면 여자친구한테 보여주고 싶은 글이네요.

**Comment by johngrib** [comment]
> 이게 번역 글은 아니지요? 영어가 원문이면 여자친구한테 보여주고 싶은 글이네요.

제가 작성한 글입니다.

**Comment by koyang2e** [comment]
옆에서 어찌어찌 번역해서 설명해주니까 굉장히 흥미로워하네요. 좋은 글 고마워요!
