### ISSUE TITLE
댓글이 달리지 않는 문제

### ISSUE THREAD

**Issue by jihunroh** [johngrib/johngrib.github.io#12]
<img width="585" alt="default" src="https://user-images.githubusercontent.com/15304946/38172459-db3356a2-35e7-11e8-97b3-8f402cd3f738.PNG">

댓글이 달리지 않습니다.

**Comment by johngrib** [comment]
utterances가 github 인증 모델을 변경하여 발생한 문제입니다. utterances 홈페이지에서 가이드하는대로 install을 실행하였더니 문제가 해결되었습니다. 확인 부탁드립니다.

**Comment by jihunroh** [comment]
댓글이 달렸습니다. 빠른 해결 감사합니다.
