### ISSUE TITLE
나의 책꽂이, 양말 서랍, 옷장 관리 방법

### ISSUE THREAD

**Issue by znagadeon** [johngrib/johngrib.github.io#156]
안녕하세요 :)

`페이지 인덱싱` 문단이 엉뚱한 데 들어가 있습니다.

![스크린샷 2021-05-31 18 56 12](https://user-images.githubusercontent.com/10708161/120176192-f68c8880-c241-11eb-8068-e072c5bc0f06.png)

**Comment by johngrib** [comment]
감사합니다. 수정했습니다.
