### ISSUE TITLE
실험하며 공부하는 GIT

### ISSUE THREAD

**Issue by Jusung** [johngrib/johngrib.github.io#170]

**Comment by johngrib** [comment]
감사합니다. 확인해보고 조만간 잘못된 내용 수정할게요.

**Comment by Jusung** [comment]
헉... 지웠었는데... 댓글 달아주셨네요. 감사합니다.

**Comment by johngrib** [comment]
@Jusung 알려주신 내용은 제가 나중에 공부해서 더 채워넣을게요. 잘못된 정보는 간단하게 수정을 했고, @Jusung님과 이 이슈를 링크했습니다. 감사합니다.
https://github.com/johngrib/johngrib.github.io/commit/295bb1ab76a57a827495b86c8893b431878d362d
