### ISSUE TITLE
편리한 git alias 설정하기 - regex 질문

### ISSUE THREAD

**Issue by GuruneLee** [johngrib/johngrib.github.io#202]
안녕하세요, git alias글에 답글 달아주셔서 감사합니다 ㅎ
제가 단 댓글에 오타가 있어 다시 여기에 여쭤봅니다

글 본문엔 `git branch | grep -v '^\\*';` 이런식으로 `^\\*` 라고 나와있어서 여쭤본것이었습니다!

이미지는 본문 캡쳐본 입니다
![image](https://user-images.githubusercontent.com/60911416/182176353-2346e734-deac-4a39-bd15-3b6908dbf3d0.png)

감사합니다.

**Comment by GuruneLee** [comment]
(제가 달았던 댓글)
![image](https://user-images.githubusercontent.com/60911416/182176725-1a90ba69-8929-4f73-ad53-386162484f5b.png)

댓글에 `^\*` 라고 써져있는 부분은 모두 `^\\*` 라고 입력한 것이었는데, md파일이라 `\\`를 백틱으로 감싸지 않으면 `\`라고 보이더군요.\
혼란을 드려 죄송합니다..ㅎ

**Comment by johngrib** [comment]
@GuruneLee 아 그래서 그런 거였군요. 제가 `^\\*` 처럼 한 이유는 git alias 정의를 " " 로 감싸진 문자열 안쪽에 작성했기 때문입니다. `\` 를 이스케이프해야 했어요. 쌍따옴표로 감싼 게 아니었다면 그냥 `^\*` 이렇게 했을 거에요.

**Comment by GuruneLee** [comment]
아하! 
문자열 안에서 \도 키워드 중 하나군요.

많은 도움이 됐습니다 감사합니다
