### ISSUE TITLE
HHKB jp 컨트롤 보드를 tmk로 교체해 보았다.

### ISSUE THREAD

**Issue by joosooyoon** [johngrib/johngrib.github.io#33]
안녕하세요. 해당 제품을 구매하고 싶은데...혹시 제작 하나 가능하신지요? ㅠㅠ 제가 너무 막손이라ㅠㅠ
혹시 가능하시면.. 카톡 ssalinun 연락 주세요.
무례한 부탁드려 죄송합니다.

**Comment by johngrib** [comment]
이거 제작하면 재료값만 50만원 이상 나갑니다. 직접 작업하시는 걸 추천드려요. 다행히 납땜 작업은 없습니다. 드라이버로 나사 풀었다 끼워 맞추는 일만 할 수 있으면 직접 할 수 있습니다. 펌웨어 빌드도 생각보다 쉬워요.
