### ISSUE TITLE
[건의사항] 문서 우측 상단 updated 를 누르면 가장 최근 변경분을 보여주는 링크로 연결

### ISSUE THREAD

**Issue by roeniss** [johngrib/johngrib.github.io#389]
### AS-IS

![Screenshot 2023-04-04 at 02 27 39 by seonghyeok](https://user-images.githubusercontent.com/26613280/229583424-cb183f22-81fd-4df6-81b6-51a01954f8d3.png)

위 이미지속 링크를 누를 시 

https://github.com/johngrib/johngrib.github.io/blame/master/_wiki/better-work/2023.md

로 연결됩니다.

그러나 이는 updated 된 게 무엇인지 잘 보여주지 못합니다.

### TO-BE 

https://github.com/johngrib/johngrib.github.io/commit/3e0dcadf6a23b401649fe89b75508f728f0a88d2

이 링크로 연결되는게 좋지 않을까 생각해 봤습니다. 명확하게 last updated content 를 보여줍니다.

+) 링크가 멋대로 커밋해쉬값으로 줄어드네요ㅋㅋ. `https://github.com/johngrib/johngrib.github.io/commit/3e0dcadf6a23b401649fe89b75508f728f0a88d2` 입니다. 

참고로 저는 위 주소를 아래 이미지처럼 찾았습니다.

![Screenshot 2023-04-04 at 02 29 57 by seonghyeok](https://user-images.githubusercontent.com/26613280/229583915-e2410d81-90cc-43ec-975e-a958a5372038.png)

**Comment by johngrib** [comment]
좋은 생각 같습니다. 다만 recent commit을 보여주는 것보다 history를 보여주는 방향으로 수정하도록 하겠습니다. 

https://github.com/johngrib/johngrib.github.io/commits/master/_wiki/better-work/2023.md

**Comment by roeniss** [comment]
@johngrib history가 낫다고 판단하신 이유가 궁금합니다. 저는 저 링크를 누른 의도가 "딱 이번 업데이트에만 반영된 걸 보고싶다" (기존 내용은 봐서) 였거든요. 다른 니즈가 더 크다고 생각하신건지요?

**Comment by johngrib** [comment]
아뇨 저는 history가 더 보고 싶어서요.
