### ISSUE TITLE
2022년 6월부터 시작된 다리 통증에 대한 기록

### ISSUE THREAD

**Issue by SJY0917032** [johngrib/johngrib.github.io#410]
안녕하세요! 평소에 블로그를 잘 보고있는 독자 1인입니다..

`2022-09 ~ 2022-12: 다리 문제를 방치한 기간` 파트의 퇴사 및 입사 년도가 22년으로 적혀있는데. `2023년 기록` 이직관련 기록에는 23년으로 나와있어 이슈 올립니다

**Comment by johngrib** [comment]
그러게요. 년도에 오타가 있었네요. 감사합니다.
