### ISSUE TITLE
Vimwiki + Jekyll + Github.io로 나만의 위키를 만들자

### ISSUE THREAD

**Issue by daniel00** [johngrib/johngrib.github.io#428]
johngrib님의 자료들을 보며 위키를 만들어 보고 있습니다. 좋은 글 늘 감사드립니다.
위키제작중 몇 가지 궁금한 점이 있어서 문의 드립니다.

1. 구글검색 말고 jekyll에서 지원하는 다른 검색방식을 사용하려면 어떻게 해야 할까요?
- 제가 뭔가를 잘못한건지 구글 검색을 위해 sitemap 을 등록해도 일괄 인덱싱이 되지 않아, 페이지를 하나씩 인덱싱 요청하고 있습니다.
이게 불편해서 다른 검색 방법을 찾아보니 jekyll 테마등에서는 search plugin을 이용해서 검색하는 방법이 있는것 같은데 우리 위키에는 어떻게 적용해야 할지를 몰라 문의드립니다.

2. 마크다운 헤더에 붙는 "점여섯개", "점두개(콜론)" 마크를 없애거나 다른 모양으로 바꾸려면 어떻게 해야 할까요?

긴글 읽어주셔서 감사합니다.

**Comment by johngrib** [comment]
discussions에 답글을 남겼습니다.
https://github.com/johngrib/johngrib.github.io/discussions/351#discussioncomment-8034457
