### ISSUE TITLE
행렬

### ISSUE THREAD

**Issue by kimpi32** [johngrib/johngrib.github.io#47]
덧붙입니다.

(0-1)행렬(Zero-one) Matrix의 경우 
(0,1)의 두 수로 이루어진 체(Field) 위에서의 행렬처럼 생각하는 것이 조금 더 자연스럽습니다.

이 Field는 덧셈과 곱셈에 대해 닫혀있고, 항등원 역원이 존재하며 교환 결합, 분배법칙이 성립하는 대상으로 구체적인 예시로는 유리수, 실수, 복소수가 있습니다. 보통 (나머지가 없는)나눗셈을 정의할 수 있느냐의 여부에 따라 체인지 아닌지가 결정되며, 정수 집합의 경우 5를 2로 나눌 수 가 없어서(나머지가 발생하기 떄문에) 정수 집합은 체가 아닙니다.

그러나, 정수 집합의 부분집합으로 (0,1,2), (0,1) 과 같은 집합은 0으로 나누기를 제외한 모든 나눗셈을 정의할 수 있기 때문에 체 구조를 가집니다.

부울 대수의 경우 (0,1)로 이루어진 체 위에서 계산한다 라고 이해하는 편이 좀 더 자연스럽습니다.

**Comment by johngrib** [comment]
감사합니다 😃
