### ISSUE TITLE
Vim, 두 가지 관점

### ISSUE THREAD

**Issue by wafe** [johngrib/johngrib.github.io#70]
와.. 엄청난 글에 놀랐습니다. 
요즘 서버 작업이 늘면서 vim 을 많이 쓰게 되어서 관련 검색을 하는 일이 많아요. 
운영 서버라서 ssh로만 접속하는 우분투 16에 vim만 설치한 상태에서 권할만한 세팅은 혹시 어떤 게 있을지 여쭤보고 싶어요. 
플러그인 관리자라던지.. 검색이나 자동완성 플러그인이라던지..

**Comment by johngrib** [comment]
저는 주로 제 개인용 로컬 컴퓨터에서 vim을 쓰는 시간이 압도적으로 많아서, 이 글에서 다룬 내용을 서버에서 다 실천하기엔 어려움이 많습니다. 서버에서는 vimscript로만 돌아가는 플러그인을 선택하는 편이 좋다고 생각합니다. 따라서 유명 플러그인 관리자 중에서는 다른 랭귀지 의존이 없는 [vim-pathogen](https://github.com/tpope/vim-pathogen)이 적절할 것 같습니다. 검색은 grep이나 find를 잘 활용하는 것으로도 아쉬움을 달랠 수 있을 것이고요. 자동완성은 vim 기본 완성 외에는 큰 기대를 하지 않는 것이 좋을듯 합니다. 다만 만약 서버에서 python을 쓰고 있다면 youcompleteme나 deoplete를 쓸 수 있을 것이고, node.js를 쓴다면 coc.nvim을 쓸 수 있을 것 같습니다. 그러나 역시 가장 중요한 것은 혼자 결정하지 않는 것이겠지요.

**Comment by wafe** [comment]
> 그러나 역시 가장 중요한 것은 혼자 결정하지 않는 것이겠지요.

가장 중요한 부분을 일깨워주셔서 감사합니다. :)

**Comment by wafe** [comment]
관심이 생겨서 좀 pathogen 을 좀 찾다보니 vim 8 에는 동일한 방식의 내장 패키지 관리가 들어갔네요. pathogen 저장소에는 vim 8 기본패키지 관리 방식을 쓰는걸 권하고 있고요.
